### PR TITLE
More examples: Example for regression and multiclass classification

### PR DESCRIPTION
**Pull request by Shammi270787**
Please check now.

### CODE REVIEW

**Comment by fraimondo** [comment]
Now the tests are running. So that problem is fixed. However, your code is not compliant with PEP8. Check 2.5 [here](https://juaml.github.io/julearn/contributing.html#contributing-with-a-pull-request).

If you run `flake8`, it will tell you which are the errors that prevent the tests to pass.

**Comment by Shammi270787** [comment]
Ah.. Ya, I get it. I will check for errors. I would like to ask you two questions.
1. Actual vs predicted plot: Should I do it for test data (by initially dividing data in train and test split).
2. Should I put the confound removal thing in a separate example? This example is already too long.

**Comment by Shammi270787** [comment]
Can you please review these examples?

**Comment by fraimondo** [comment]
I'll review it today.

**Pull request merged**
