### PR TITLE
ADD test showing #94

### PR DESCRIPTION
**Pull request by samihamdan**

### CODE REVIEW

**Comment by fraimondo** [comment]
Update what's new. Add it as a bug fix.

**Comment by samihamdan** [comment]
Yes I have it local already its commit when everything is green :+1:

**Comment by samihamdan** [comment]
Did I add it correctly to the bugfixes ? @fraimondo

**Review by fraimondo — CHANGES_REQUESTED** [review]

**Review by fraimondo — APPROVED** [review]

**Comment by fraimondo** [comment]
Once travis is green, LGTM!

**Pull request merged**
