### PR TITLE
Freeze requirements

### PR DESCRIPTION
**Pull request by samihamdan**

### CODE REVIEW

**Comment by fraimondo** [comment]
Are we sure that this is the best? Why not asking for >=?

**Comment by samihamdan** [comment]
Correct me if I am wrong, but :
`sklearn>=0.23.2`
would mean  that it installs a higher version e.g. 0.24 when available. 
The problem is that changes in sklearn can break julearn as it just happened. 
Main is red, while we did not change anything. It was running/green before the new version existed. 
When I am reverting it back to 0.23.2 it works again. 

So from my perspective it is a risk to automatically install newer versions without checking them first. 
If there is a better solution I am happy to take it though.

**Comment by kaurao** [comment]
I think expected this to happen at some stage but not so soon :D
There are two possibilities 

- sklearn is installed with julearn and in that case we can control the version to be installed
- sklearn is already satisfied in which case we have to check for compatibility within code

**Comment by fraimondo** [comment]
Indeed that would break if there is a compatibility issue.

On the other hand, being very strict with versions makes it almost impossible to have an environment due to conflicts in required versions. When sklearn releases, we need to update and release. And that's how me make it work.

So now we should have an issue "julearn not compatible with sklearn 0.24". We then update julearn to be compatible with sklearn 0.24 and make a new release.

**Comment by samihamdan** [comment]
So, we just allow the pip installable version of julearn to be able to break whenever a dependency changes ?

**Comment by fraimondo** [comment]
I'm checking what other python projects do. Indeed they all specify a minimum version. Both solution have issues.

If you fix sklearn and pandas, and then a third package needs sklearn and pandas, but with different numbers, you won't be able to have it in the same environment. So that's why the >= approach is more flexible.

On the other hand, it's also possible that a new release of a package might break julearn. So you end up with non-working environment. However, the answer is always "wait for the new release and update everything to the latest version". And this is not a problem since we will have to update julearn every time sklearn releases (that's the main reason to avoid many dependencies and always keep the project under development). If a user needs a specific version of sklearn (older than latest), then there's always the option to downgrade julearn. This is also what you obtain with `pip freeze` and why I log version of the installed (useful) packages in the logging module. We need to keep up with the latest. Not with the previous ones.

**Comment by samihamdan** [comment]
I understand the problem and for everything but sklearn I agree that we should not keep it fixed, because of it. 
(also there will not be a big risk of pandas or numpy breaking julearn)
 
For sklearn I'm not sure:

If we have to update julearn whenever sklearn updates, then why not keep it fixed for the short delay until we can make it work again.

I don't see that downgrading julearn works. 
If julearn always installs the newest version of sklearn then old releases will not work as well as soon as sklearn upgrade.
You can freez or manually downgrade sklearn, but this is not user-friendly.
If I would be a user I would be devastated if it just stops working and I don't know why. 
Reinstalling would not solve it, downgrading would not solve it. 
  

But lets discuss it in detail when you're back. 
For now I will close this PR, because I agree that pushing it before discussing it more makes no sense (and maybe freezing any decency makes no sense)

**Pull request closed without merging**
